### ISSUE TITLE
[Feature Request] Report instead of comments

### ISSUE THREAD

**Issue by FerdinandoLM** [GermainZ/Taskerbot#1]
I wonder if there is a way to use reports instead of comments to trigger the bot.

eg: Report from Moderator: @rule 1 

and it removes the comment or the thread where the report has been placed

**Comment by GermainZ** [comment]
The API would allow it, but we wanted to add a logging-to-wiki feature (319aec7f0e321b74cbd91cff6127f02062edd7cd) and reports (including mod reports) are anonymous which would make that impossible. Sorry! :(

**Comment by FerdinandoLM** [comment]
Wait, if a moderator does a report it is not anonymous. the name of the moderator appears: 

http://i.imgur.com/yQC6SJ4.png

**Comment by GermainZ** [comment]
Added in e7ee3d067c362fda2f290068655365ae6b3a9df9. Please note the following limitation:

>PS. Reddit silently ignores reports on removed posts, so Taskerbot won't see those.
