### ISSUE TITLE
Reports not being handled

### ISSUE THREAD

**Issue by austind9999** [GermainZ/Taskerbot#10]
Taskerbot is not acting on the moderator reports with the @rule commands. It works for comments just fine.

**Comment by jessicarod7** [comment]
This should be closed, the issue is better described in #11.

**Comment by austind9999** [comment]
This issue is separate. After further testing reports by moderators are found only about 50% of the time. The common theme is that posts reported that have no prior reports are removed almost 100% of the time while any post that has a previous report is removed close to 0% of the time. There are no errors given when it has skipped a report.

**Comment by GermainZ** [comment]
>any post that has a previous report is removed close to 0% of the time

Are the previous reports from users or other mods?

**Comment by austind9999** [comment]
The previous reports are user reports.

**Comment by austind9999** [comment]
So I ended up needing to start a new instance of the bot which seems to have resolved this issue. Must have been something on my end causing this.
