### ISSUE TITLE
New Reddit replaces @ with u/

### ISSUE THREAD

**Issue by austind9999** [GermainZ/Taskerbot#11]
This does not work on new Reddit as @ is now auto replaced with u/ with no way to prevent it. Recommend changing the command to ! which works correctly.

**Comment by jessicarod7** [comment]
[Here's a video showing the behaviour.](https://i.imgur.com/MsKBjf0.mp4). The Fancy Pants editor overrides any use of the @ symbol, even typing in text with the @ symbol, and then removing the surrounding text.

**Comment by GermainZ** [comment]
As of f358dee466eebc0dcbbb63c942758246de541cfc you can now use `!` or `@`.
